### ISSUE TITLE
NullPointerException in TLoadBalancerClient

### ISSUE THREAD

**Issue by Salmondx** [aatarasoff/spring-thrift-starter#21]
Exception occurs when there is no service with such name in service registry.
Here:
```java
HttpURLConnection iox = 
    (HttpURLConnection) new URL(this.loadBalancerClient.choose(serviceName)
        .getUri().toString() + path).openConnection();
```
`loadBalancerClient.choose(serviceName)` returns null.

https://github.com/aatarasoff/spring-thrift-starter/blob/60bab1f92fca926ade509a36961a468a62f4d3df/autoconfigure/src/main/java/info/developerblog/spring/thrift/transport/TLoadBalancerClient.java

**Comment by aatarasoff** [comment]
Fixed in https://github.com/aatarasoff/spring-thrift-starter/pull/22
