### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by TobiasBales** [aatarasoff/spring-thrift-starter#40]
Is this package still maintained?

We are looking into using something similar but would like to extend e.g. the collected metrics and I was curious if it made sense to trying to contribute or if simply forking might be the easier option.

**Comment by aatarasoff** [comment]
Hi! I do not maintain it in a regular way. But I check and accept pull requests from other developers and release new versions into jcenter. So the best way if you fork the project, do something useful and make PR with these changes.

**Comment by TobiasBales** [comment]
Okay cool. I submitted a pull-request that adds more metrics and left the original gauge in place to not break existing consumers. If you want me to change anything, do let me know :)
